### ISSUE TITLE
Docker image for Arm64 platform is required 

### ISSUE THREAD

**Issue by odidev** [brigadecore/kaniko#4]
Hi Team,
I am trying to use the Kaniko image on arm64 platform but it seems it is not available for arm64.
I have successfully built the image using the command `docker build -t <image_name>` . on the arm64 platform with small changes in the Dockerfile.
Commit Link -  4319692e3fd414b32b05ce3052e7b713126918ce
Docker Hub Link -  https://hub.docker.com/repository/docker/odidev/kaniko
Do you have any plans on releasing arm64 images?
May I know how the amd64 image is getting published on Dockerhub?
If interested, I will raise a PR.

**Comment by odidev** [comment]
@krancour , can you please look at above issue?

**Comment by krancour** [comment]
@odidev I believe we've had conversations about this before in other threads. Please understand that we cannot be forced into prioritizing arm64 support just by you opening more issues against more of our repos.

We _are_ interested in arm64 support and intend to pursue it when we are able, but at present we do not have arm64 VMs at our disposal. Our hands are kind of tied until that changes.

**Comment by krancour** [comment]
@odidev my apologies if my response came off as harsh. I did not mean for it to.

We're just kinda _stuck_ at the moment in a place where we don't have the infrastructure we need to do this.

Despite our love of "dogfooding" Brigade, these simple "helper images" like `go-tools`, `kaniko`, `helm-tools`, etc. are outliers in that we're letting DockerHub build these for us...

When time allows, I'll take a look at what it would take (or if it's even possible) to do multiarch builds directly _on_ DockerHub. If it's possible, these would be the first baby steps toward arm64 support-- and they'd be steps taken partly on faith because we don't have the means to even validate the arm64 images at the moment.

**Comment by krancour** [comment]
We've unfortunately taken a step backward on this. Due to Docker pricing, we no longer automate any builds through DockerHub and we do _everything_ with our "dogfood" Brigade cluster.

We still do not have arm64 VMs at our disposal.

I'm going to close this and allow the issue to be subsumed by a larger effort to get all of Brigade working on arm64 post v2.
